using Bombd.Helpers;

namespace Bombd.Types.Network.Objects;

public class AiDefinition
{
    public static AiDefinition[] KartingDefinitions =
    {
        new() { Name = "Hoardsmith", Profile = "MID" },
        new() { Name = "Hoardymore", Profile = "MID" },
        new() { Name = "Hoardratio", Profile = "MID" },
        new() { Name = "Hoardsworth", Profile = "MID" },
        new() { Name = "Hoardsley", Profile = "MID" },
        new() { Name = "Hoardriguez", Profile = "MID" },
        new() { Name = "Hoardoza", Profile = "MID" },
        new() { Name = "Hoardnandez", Profile = "MID" },
        new() { Name = "Hoardazar", Profile = "MID" },
        new() { Name = "Hoardford", Profile = "MID" },
        new() { Name = "Sir Hoardelot", Profile = "MID" },
        new() { Name = "Sir Hoardfort", Profile = "MID" },
        new() { Name = "Sir Hoardbeard", Profile = "MID" },
        new() { Name = "Sir Hoardamere", Profile = "MID" },
        new() { Name = "P. Hoarderson", Profile = "MID" },
        new() { Name = "Hoard-san", Profile = "MID" },
        new() { Name = "Hoardsama", Profile = "MID" },
        new() { Name = "Hoardshi", Profile = "MID" },
        new() { Name = "Hoardsaki", Profile = "MID" },
        new() { Name = "Hoardyama", Profile = "MID" },
        new() { Name = "Hoardkun", Profile = "MID" },
        new() { Name = "Hoardzuki", Profile = "MID" },
        new() { Name = "Hoardoki", Profile = "MID" },
        new() { Name = "Hoardfrey", Profile = "MID" },
        new() { Name = "Hoardinald", Profile = "MID" },
        new() { Name = "Hoardtrude", Profile = "MID" },
        new() { Name = "Grace Hoard", Profile = "MID" },
        new() { Name = "Franklin Hoard", Profile = "MID" },
        new() { Name = "Susie Hoard", Profile = "MID" },
        new() { Name = "Grant Hoard", Profile = "MID" },
        new() { Name = "Captain Hoard", Profile = "MID" },
        new() { Name = "General Hoard", Profile = "MID" },
        new() { Name = "Marshal Hoard", Profile = "MID" },
        new() { Name = "Major Hoard", Profile = "MID" },
        new() { Name = "Hoardimer", Profile = "MID" },
        new() { Name = "Hoardette", Profile = "MID" },
        new() { Name = "Hoardhouse", Profile = "MID" },
        new() { Name = "Hoardmund", Profile = "MID" },
        new() { Name = "Hoardprice", Profile = "MID" },
        new() { Name = "Hoardenstein", Profile = "MID" },
        new() { Name = "Unhoarded", Profile = "MID" },
        new() { Name = "Hoardblood", Profile = "MID" },
        new() { Name = "Hoardberry", Profile = "MID" },
        new() { Name = "Spatiohoard", Profile = "MID" },
        new() { Name = "Astrohoard", Profile = "MID" },
        new() { Name = "Cosmohoard", Profile = "MID" },
        new() { Name = "Xenohoard", Profile = "MID" },
        new() { Name = "Hoardotron", Profile = "MID" },
        new() { Name = "Hoards McGee", Profile = "MID" },
        new() { Name = "Hoardelle", Profile = "MID" },
        new() { Name = "Hoardheart", Profile = "MID" },
        new() { Name = "Hoardington", Profile = "MID" },
        new() { Name = "Hoardlinger", Profile = "MID" },
        new() { Name = "Hoardalina", Profile = "MID" },
        new() { Name = "Hoardacus", Profile = "MID" },
        new() { Name = "Hoardiana", Profile = "MID" },
        new() { Name = "Hoardentine", Profile = "MID" },
        new() { Name = "Hoardemis", Profile = "MID" },
        new() { Name = "Hoard Emperor", Profile = "MID" },
        new() { Name = "Hoard Prince", Profile = "MID" },
        new() { Name = "Baron Hoard", Profile = "MID" },
        new() { Name = "Rex Hoard", Profile = "MID" },
        new() { Name = "Duke of Hoard", Profile = "MID" },
        new() { Name = "Duke Hoardley", Profile = "MID" },
        new() { Name = "Hoard Tsar", Profile = "MID" },
        new() { Name = "Hoard Dauphin", Profile = "MID" },
        new() { Name = "Viscount Hoard", Profile = "MID" },
        new() { Name = "Hoard Queen", Profile = "MID" },
        new() { Name = "Hoard Baroness", Profile = "MID" },
        new() { Name = "Lord Hoard", Profile = "MID" },
        new() { Name = "Hoard King", Profile = "MID" },
        new() { Name = "CreateBot 1", Profile = "MID" },
        new() { Name = "CreateBot 2", Profile = "MID" },
        new() { Name = "CreateBot 3", Profile = "MID" },
        new() { Name = "CreateBot 4", Profile = "MID" },
        new() { Name = "CreateBot 5", Profile = "MID" },
        new() { Name = "CreateBot 6", Profile = "MID" },
        new() { Name = "CreateBot 7", Profile = "MID" },
        new() { Name = "Botsworth", Profile = "MID" },
        new() { Name = "Sackbuddy", Profile = "MID" },
        new() { Name = "Robbie-bot", Profile = "MID" },
        new() { Name = "Speedy-bot", Profile = "MID" },
        new() { Name = "Cutie-bot", Profile = "MID" },
        new() { Name = "Sacksmith", Profile = "MID" },
        new() { Name = "Dannie-bot", Profile = "MID" },
        new() { Name = "Sackbert", Profile = "MID" },
        new() { Name = "Sackington", Profile = "MID" },
        new() { Name = "Mr. Sack", Profile = "MID" },
        new() { Name = "Sack-o-matic", Profile = "MID" },
        new() { Name = "Sackbot #6", Profile = "MID" },
        new() { Name = "Sackie #5", Profile = "MID" },
        new() { Name = "Sackman", Profile = "MID" },
        new() { Name = "Sacktron", Profile = "MID" },
        new() { Name = "Sackalicious", Profile = "MID" },
        new() { Name = "Sackson", Profile = "MID" },
        new() { Name = "Sackspeare", Profile = "MID" },
        new() { Name = "Bunny", Profile = "MID" },
        new() { Name = "The Bride", Profile = "MID" },
        new() { Name = "Hoardez", Profile = "MID" },
        new() { Name = "Hoardelita", Profile = "MID" },
        new() { Name = "Hoardonso", Profile = "MID" },
        new() { Name = "Hoardstone", Profile = "MID" },
        new() { Name = "Hoardmont", Profile = "MID" },
        new() { Name = "Hoard Dude", Profile = "MID" },
        new() { Name = "Hoardselhoff", Profile = "MID" },
        new() { Name = "Hoard Scheider", Profile = "MID" },
        new() { Name = "Hoardsashi", Profile = "MID" },
        new() { Name = "Hoardamoto", Profile = "MID" },
        new() { Name = "Hoardugawa", Profile = "MID" },
        new() { Name = "Hoardunaga", Profile = "MID" },
        new() { Name = "Hoardshido", Profile = "MID" },
        new() { Name = "Hoardosawa", Profile = "MID" },
        new() { Name = "Hoardira", Profile = "MID" },
        new() { Name = "Zahoardichi", Profile = "MID" },
        new() { Name = "Hoardginia", Profile = "MID" },
        new() { Name = "Nikola Hoardsla", Profile = "MID" },
        new() { Name = "Alex G. Hoard", Profile = "MID" },
        new() { Name = "Ben Hoardlin", Profile = "MID" },
        new() { Name = "Isaac Hoardton", Profile = "MID" },
        new() { Name = "Hoardini", Profile = "MID" },
        new() { Name = "Hoardbert", Profile = "MID" },
        new() { Name = "Hoardothy", Profile = "MID" },
        new() { Name = "Hoardelia", Profile = "MID" },
        new() { Name = "Hoardmero", Profile = "MID" },
        new() { Name = "Hoardodendron", Profile = "MID" },
        new() { Name = "Hoardenia", Profile = "MID" },
        new() { Name = "Hoardchard", Profile = "MID" },
        new() { Name = "Hoardfly", Profile = "MID" },
        new() { Name = "Hoardsquito", Profile = "MID" },
        new() { Name = "Hoarderpillar", Profile = "MID" },
        new() { Name = "Hoardipede", Profile = "MID" },
        new() { Name = "N. Hoardstrong", Profile = "MID" },
        new() { Name = "B. Hoardrin", Profile = "MID" },
        new() { Name = "Hoardentina T.", Profile = "MID" },
        new() { Name = "Y. Hoardarin", Profile = "MID" },
        new() { Name = "Dr. Hoardbot", Profile = "MID" },
        new() { Name = "Mecha Hoard", Profile = "MID" },
        new() { Name = "Henry Hoard", Profile = "MID" },
        new() { Name = "Prof Hoardard", Profile = "MID" },
        new() { Name = "Hoard Robinson", Profile = "MID" },
        new() { Name = "James T. Hoard", Profile = "MID" },
        new() { Name = "Hoard Rogers", Profile = "MID" },
        new() { Name = "Freddie Hoardury", Profile = "MID" },
        new() { Name = "Disco Hoard", Profile = "MID" },
        new() { Name = "Hoardtown", Profile = "MID" },
        new() { Name = "Hoardey M.", Profile = "MID" },
        new() { Name = "Hoardie Oakley", Profile = "MID" },
        new() { Name = "Wyatt Hoard", Profile = "MID" },
        new() { Name = "Hoard Wayne", Profile = "MID" },
        new() { Name = "Hoardlie the Kid", Profile = "MID" },
        new() { Name = "Sofie", Profile = "MID" },
        new() { Name = "Miles", Profile = "MID" },
        new() { Name = "Alex", Profile = "MID" },
        new() { Name = "Chip", Profile = "MID" },
        new() { Name = "Wannabee", Profile = "MID" },
        new() { Name = "Baconbeard", Profile = "MID" },
        new() { Name = "Sebastian", Profile = "MID" },
        new() { Name = "Alvin", Profile = "" },
        new() { Name = "Scales", Profile = "" },
        new() { Name = "Wilber", Profile = "MID" },
        new() { Name = "Sackbeard", Profile = "MID" },
        new() { Name = "Hoard Minion 1", Profile = "MID" },
        new() { Name = "Hoard Minion 2", Profile = "MID" },
        new() { Name = "Hoard Minion 3", Profile = "MID" },
        new() { Name = "Hoard Minion 4", Profile = "MID" },
    };
    
    public static AiDefinition[] ModnationDefinitions =
    {
        new() { Name = "Shadow", Profile = "SHADOWonVISTAPOINT" },
        new() { Name = "Fade", Profile = "FADEonMARKETRUN" },
        new() { Name = "Dolor", Profile = "DOLORonRUMBLEISLAND" },
        new() { Name = "Nato", Profile = "NATOonSINKHOLE" },
        new() { Name = "Drillbit", Profile = "DrillbitonMINERSRIFT" },
        new() { Name = "Iceman", Profile = "ICEMANonCRAGGYHILLS" },
        new() { Name = "Skidplate", Profile = "SKIDPLATEonBOARDWALK" },
        new() { Name = "Wildcard", Profile = "WILDCARDonMOTOCROSSISLAND" },
        new() { Name = "Hale", Profile = "HALEonFLAMINGJUMPS" },
        new() { Name = "Scout", Profile = "SCOUTonRICKETYBRIDGE" },
        new() { Name = "Slick", Profile = "SLICKonSANDSTORM" },
        new() { Name = "Aloha", Profile = "ALOHAonTEMPLEOFTIKI" },
        new() { Name = "Dyno", Profile = "DYNOonMARINA" },
        new() { Name = "Espresso", Profile = "MAX" },
        new() { Name = "Diablo", Profile = "DIABLOonSPEEDWAYSPRINGS" },
        new() { Name = "A-Mach", Profile = "MID" },
        new() { Name = "Lolley", Profile = "MID" },
        new() { Name = "Cosmo", Profile = "MID" },
        new() { Name = "Parka", Profile = "MID" },
        new() { Name = "Emao III", Profile = "MID" },
        new() { Name = "JZee", Profile = "MID" },
        new() { Name = "Shotz", Profile = "MID" },
        new() { Name = "S to the Eth", Profile = "MID" },
        new() { Name = "Gunder", Profile = "MID" },
        new() { Name = "Tobias Roy", Profile = "MID" },
        new() { Name = "Radu", Profile = "MID" },
        new() { Name = "Lubker", Profile = "MID" },
        new() { Name = "Spence-O-Matic", Profile = "MID" },
        new() { Name = "The Soch", Profile = "MID" },
        new() { Name = "Kozak", Profile = "MID" },
        new() { Name = "E Man", Profile = "MID" },
        new() { Name = "Vlad", Profile = "MID" },
        new() { Name = "Prime Time", Profile = "MID" },
        new() { Name = "Joesiv", Profile = "MID" },
        new() { Name = "Oz", Profile = "MID" },
        new() { Name = "Gedski", Profile = "MID" },
        new() { Name = "Chainsaw", Profile = "MID" },
        new() { Name = "Bruzer", Profile = "MID" },
        new() { Name = "Granny", Profile = "MID" },
        new() { Name = "T-Rask", Profile = "MID" },
        new() { Name = "Griller", Profile = "MID" },
        new() { Name = "The MC", Profile = "MID" },
        new() { Name = "Pip Cork", Profile = "MID" },
        new() { Name = "Hooleyman", Profile = "MID" },
        new() { Name = "Kibbler", Profile = "MID" },
        new() { Name = "Skye", Profile = "MID" },
        new() { Name = "Lish", Profile = "MID" },
        new() { Name = "Mic", Profile = "MID" },
        new() { Name = "Harry", Profile = "MID" },
        new() { Name = "Astro Kitty", Profile = "MID" },
        new() { Name = "PJ", Profile = "MID" },
        new() { Name = "Captain Venus", Profile = "MID" },
        new() { Name = "Gill", Profile = "MID" },
        new() { Name = "Shaman", Profile = "MID" },
        new() { Name = "Bionic", Profile = "MID" },
        new() { Name = "A.N.T.", Profile = "MID" },
        new() { Name = "Gargles", Profile = "MID" },
        new() { Name = "Nails", Profile = "MID" },
        new() { Name = "Abranda", Profile = "MID" },
        new() { Name = "Marvin", Profile = "THUG" },
        new() { Name = "Robbie", Profile = "THUG" },
        new() { Name = "Max", Profile = "THUG" },
        new() { Name = "Hal", Profile = "THUG" },
        new() { Name = "Sven", Profile = "THUG" },
        new() { Name = "Bjorn", Profile = "THUG" },
        new() { Name = "Gustav", Profile = "THUG" },
        new() { Name = "Erik", Profile = "THUG" },
        new() { Name = "Kristoffer", Profile = "THUG" },
        new() { Name = "Clyde", Profile = "THUG" },
        new() { Name = "Robin", Profile = "THUG" },
        new() { Name = "Jesse", Profile = "THUG" },
        new() { Name = "Carmen", Profile = "THUG" },
        new() { Name = "Butch", Profile = "THUG" },
        new() { Name = "Flynn", Profile = "THUG" },
        new() { Name = "Ricky", Profile = "THUG" },
        new() { Name = "Danny", Profile = "THUG" },
        new() { Name = "Billy", Profile = "THUG" },
        new() { Name = "Bobby", Profile = "THUG" },
        new() { Name = "Johnny", Profile = "THUG" },
        new() { Name = "Andy", Profile = "THUG" },
        new() { Name = "Timmy", Profile = "THUG" },
        new() { Name = "Beezel", Profile = "THUG" },
        new() { Name = "Deezel", Profile = "THUG" },
        new() { Name = "Weezel", Profile = "THUG" },
        new() { Name = "Meezel", Profile = "THUG" },
        new() { Name = "Teezel", Profile = "THUG" },
        new() { Name = "Zeezel", Profile = "THUG" },
        new() { Name = "Neezel", Profile = "THUG" },
        new() { Name = "Reezel", Profile = "THUG" }
    };

    public string Name;
    public string Profile;

    public static List<AiDefinition> GetRandomDefinitions(Platform platform, int count)
    {
        AiDefinition[] dataSet = platform == Platform.Karting ? KartingDefinitions : ModnationDefinitions;
        List<AiDefinition> definitions = new();
        HashSet<int> selected = new();

        var random = new Random();
        while (definitions.Count != count)
        {
            int index = random.Next(0, dataSet.Length);
            if (selected.Contains(index)) continue;
            definitions.Add(dataSet[index]);
            selected.Add(index);
        }

        return definitions;
    }
}